//go:build integration

package integration

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestDevices_Create_Valid(t *testing.T) {
	cleanDB(t)
	custID, custToken := createCustomer(t, "Dev Alice", "dev.alice@test.com", "93500001", "560501")
	resp := makeRequest(t, "POST", "/api/customeraircondevices/", map[string]interface{}{
		"customerId": custID, "airconName": "Living Room AC",
		"numberOfUnits": 2, "airconType": "daikin",
	}, custToken)
	require.Equal(t, http.StatusCreated, resp.StatusCode)
	var body map[string]interface{}
	decodeBody(t, resp, &body)
	assert.NotEmpty(t, body["id"])
}

func TestDevices_Create_DuplicateName(t *testing.T) {
	cleanDB(t)
	custID, custToken := createCustomer(t, "Dup Dev", "dup.dev@test.com", "93500010", "560510")
	createDevice(t, custID, "Master AC", custToken)
	resp := makeRequest(t, "POST", "/api/customeraircondevices/", map[string]interface{}{
		"customerId": custID, "airconName": "Master AC", "numberOfUnits": 1,
	}, custToken)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
}

func TestDevices_Create_TooManyUnits(t *testing.T) {
	cleanDB(t)
	custID, custToken := createCustomer(t, "Units Dev", "units.dev@test.com", "93500020", "560520")
	resp := makeRequest(t, "POST", "/api/customeraircondevices/", map[string]interface{}{
		"customerId": custID, "airconName": "Big AC", "numberOfUnits": 101,
	}, custToken)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
}

func TestDevices_Create_FutureServiceMonth(t *testing.T) {
	cleanDB(t)
	custID, custToken := createCustomer(t, "Fut Dev", "fut.dev@test.com", "93500030", "560530")
	resp := makeRequest(t, "POST", "/api/customeraircondevices/", map[string]interface{}{
		"customerId": custID, "airconName": "Future AC",
		"numberOfUnits": 1, "lastServiceMonth": "2099-12",
	}, custToken)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
}

func TestDevices_Create_AutoGeneratedName(t *testing.T) {
	cleanDB(t)
	custID, custToken := createCustomer(t, "Auto Dev", "auto.dev@test.com", "93500040", "560540")
	resp := makeRequest(t, "POST", "/api/customeraircondevices/", map[string]interface{}{
		"customerId": custID, "numberOfUnits": 1, "airconType": "samsung",
		// No airconName supplied
	}, custToken)
	require.Equal(t, http.StatusCreated, resp.StatusCode)
	var body map[string]interface{}
	decodeBody(t, resp, &body)
	assert.NotEmpty(t, body["id"])
}

func TestDevices_List_FilterByCustomer(t *testing.T) {
	cleanDB(t)
	cust1ID, cust1Token := createCustomer(t, "ListD C1", "listd.c1@test.com", "93500050", "560550")
	_, cust2Token := createCustomer(t, "ListD C2", "listd.c2@test.com", "93500051", "560551")
	createDevice(t, cust1ID, "C1 AC", cust1Token)
	resp := makeRequest(t, "GET", "/api/customeraircondevices/?customerId="+cust1ID, nil, cust2Token)
	require.Equal(t, http.StatusOK, resp.StatusCode)
	var body []interface{}
	decodeBody(t, resp, &body)
	require.Len(t, body, 1)
	m := body[0].(map[string]interface{})
	assert.Equal(t, cust1ID, m["customerId"])
}

func TestDevices_Patch(t *testing.T) {
	cleanDB(t)
	custID, custToken := createCustomer(t, "Patch Dev", "patch.dev@test.com", "93500060", "560560")
	devID := createDevice(t, custID, "Patch AC", custToken)
	resp := makeRequest(t, "PATCH", "/api/customeraircondevices/"+devID+"/", map[string]interface{}{
		"numberOfUnits": 3,
	}, custToken)
	require.Equal(t, http.StatusOK, resp.StatusCode)
	var body map[string]interface{}
	decodeBody(t, resp, &body)
	assert.Equal(t, float64(3), body["numberOfUnits"])
}

func TestDevices_Delete(t *testing.T) {
	cleanDB(t)
	custID, custToken := createCustomer(t, "Del Dev", "del.dev@test.com", "93500070", "560570")
	devID := createDevice(t, custID, "Del AC", custToken)
	resp := makeRequest(t, "DELETE", "/api/customeraircondevices/"+devID+"/", nil, custToken)
	assert.Equal(t, http.StatusNoContent, resp.StatusCode)
}
