-- AirServe PostgreSQL initialization
-- Runs only on first container start (when pg_data volume is empty)

-- No extensions needed: UUIDs are generated by Python (uuid.uuid4),
-- not by PostgreSQL. All models use default=uuid.uuid4.

-- This file exists as a hook for future needs (e.g., pg_trgm for
-- full-text search, PostGIS for geo queries replacing geopy, etc.)
