from .appointment_views import AppointmentViewSet
from .coordinator_views import CoordinatorViewSet
from .customer_aircon_devices_views import CustomerAirconDeviceViewSet
from .customer_views import CustomerViewSet
from .technician_views import TechnicianViewSet
from .message_views import MessageViewSet
from .hiring_views import TechnicianHiringApplicationViewSet
