# Generated by Django 4.2.5 on 2026-03-03 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirconCatalogs',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('airconBrand', models.CharField(max_length=50)),
                ('airconModel', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['airconBrand', 'airconModel'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ratedBy', models.CharField(choices=[('technician', 'Technician'), ('customer', 'Customer')], max_length=20)),
                ('rating', models.IntegerField(help_text='1-5 stars')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('appointmentStartTime', models.BigIntegerField(help_text='Unix epoch seconds')),
                ('appointmentEndTime', models.BigIntegerField(help_text='Unix epoch seconds')),
                ('airconToService', models.JSONField(default=list, help_text='List of customerAirconDevices IDs')),
                ('customerFeedback', models.TextField(default=None, max_length=500, null=True)),
                ('appointmentStatus', models.CharField(choices=[('1', 'Pending'), ('2', 'Confirmed'), ('3', 'Completed'), ('4', 'Cancelled')], default=1, max_length=1)),
                ('paymentMethod', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paynow', 'PayLah/PayNow')], default='cash', help_text='Customer selected payment method', max_length=20)),
                ('cancellationReason', models.TextField(blank=True, default=None, help_text='Reason for cancellation', max_length=500, null=True)),
                ('cancelledBy', models.CharField(blank=True, help_text='Role of person who cancelled (technician/coordinator)', max_length=50, null=True)),
                ('cancelledAt', models.DateTimeField(blank=True, help_text='Timestamp of cancellation', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coordinatorName', models.CharField(max_length=50)),
                ('coordinatorEmail', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('coordinatorPhone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$')])),
                ('coordinatorPassword', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['coordinatorName'],
            },
        ),
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('technicianName', models.CharField(max_length=50)),
                ('technicianPostalCode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Postal code must be exactly 6 digits.')])),
                ('technicianAddress', models.CharField(max_length=50)),
                ('technicianLocation', models.CharField(max_length=32, null=True)),
                ('technicianPhone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be exactly 8 digits.')])),
                ('technicianEmail', models.CharField(blank=True, help_text='Email address for notifications', max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('technicianPassword', models.CharField(max_length=128)),
                ('technicianStatus', models.CharField(choices=[('1', 'Available'), ('2', 'Unavailable')], default=1, max_length=1)),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of AC brands the technician specializes in')),
                ('technicianTravelType', models.CharField(blank=True, choices=[('own_vehicle', 'Own Vehicle'), ('company_vehicle', 'Company Vehicle'), ('rental_van', 'Rental Van')], default=None, max_length=20, null=True)),
                ('technicianRating', models.DecimalField(decimal_places=2, default=5.0, help_text='Average rating from customers (1-5), default 5', max_digits=3)),
                ('technicianRatingCount', models.IntegerField(default=0, help_text='Number of ratings received from customers')),
                ('isActive', models.BooleanField(default=True, help_text='Whether technician is currently employed/active')),
                ('deactivatedAt', models.DateTimeField(blank=True, help_text='When the technician was deactivated', null=True)),
                ('deactivationReason', models.TextField(blank=True, help_text='Reason for deactivation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['technicianName'],
                'indexes': [models.Index(fields=['technicianStatus'], name='backend_api_technic_5234e8_idx'), models.Index(fields=['technicianPhone'], name='backend_api_technic_c024c8_idx'), models.Index(fields=['technicianEmail'], name='backend_api_technic_ff7cae_idx'), models.Index(fields=['technicianPostalCode'], name='backend_api_technic_0df0b7_idx'), models.Index(fields=['isActive'], name='backend_api_isActiv_eab08d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicianPasswordResetToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expiresAt', models.DateTimeField(help_text='Token expiration time')),
                ('isUsed', models.BooleanField(default=False, help_text='Whether token has been used')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='backend_api.technicians')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianHiringApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('applicationSource', models.CharField(choices=[('coordinator_invited', 'Coordinator Invited'), ('self_applied', 'Self Applied')], default='coordinator_invited', help_text='Whether coordinator invited or technician self-applied', max_length=30)),
                ('applicantName', models.CharField(help_text='Full name of applicant', max_length=100)),
                ('nric', models.CharField(help_text='NRIC number', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[STFG]\\d{7}[A-Z]$', 'NRIC must be in valid Singapore format (e.g., S1234567A)')])),
                ('citizenship', models.CharField(help_text='Citizenship status', max_length=50)),
                ('applicantAddress', models.CharField(help_text='Full residential address', max_length=200)),
                ('applicantPostalCode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Postal code must be exactly 6 digits.')])),
                ('applicantPhone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be exactly 8 digits.')])),
                ('applicantEmail', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('workExperience', models.TextField(help_text='Work experience details', max_length=2000)),
                ('resumeFile', models.FileField(blank=True, help_text='Resume upload', null=True, upload_to='resumes/')),
                ('resumeFileName', models.CharField(blank=True, help_text='Original resume filename', max_length=255, null=True)),
                ('hasCriminalRecord', models.BooleanField(default=False, help_text='Criminal record declaration')),
                ('criminalRecordDetails', models.TextField(blank=True, help_text='Details if criminal record exists', max_length=1000, null=True)),
                ('race', models.CharField(default='', help_text='Race of applicant', max_length=50)),
                ('languagesSpoken', models.CharField(default='', help_text='Languages spoken (comma-separated)', max_length=200)),
                ('previousEmployer', models.CharField(blank=True, help_text='Name of previous employer(s)', max_length=200, null=True)),
                ('lastEmployedYear', models.IntegerField(blank=True, help_text='Year when last employed', null=True)),
                ('lastDrawnSalary', models.DecimalField(blank=True, decimal_places=2, help_text='Last drawn monthly salary in SGD', max_digits=10, null=True)),
                ('nextOfKinName', models.CharField(default='', help_text='Name of next of kin', max_length=100)),
                ('nextOfKinContact', models.CharField(default='', help_text='Contact number of next of kin', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be exactly 8 digits.')])),
                ('nextOfKinRelationship', models.CharField(default='', help_text='Relationship with next of kin', max_length=50)),
                ('isMedicallyFit', models.BooleanField(default=False, help_text='Declaration of medical fitness to work')),
                ('medicalFitnessConfirmedAt', models.DateTimeField(blank=True, null=True)),
                ('profilePhoto', models.ImageField(blank=True, help_text='Profile photo of applicant', null=True, upload_to='profile_photos/')),
                ('profilePhotoFileName', models.CharField(blank=True, help_text='Original profile photo filename', max_length=255, null=True)),
                ('nricPhotoFront', models.ImageField(blank=True, help_text='NRIC front photo', null=True, upload_to='nric_photos/')),
                ('nricPhotoBack', models.ImageField(blank=True, help_text='NRIC back photo', null=True, upload_to='nric_photos/')),
                ('drivingLicense', models.ImageField(blank=True, help_text='Driving license photo', null=True, upload_to='driving_licenses/')),
                ('drivingLicenseFileName', models.CharField(blank=True, help_text='Original driving license filename', max_length=255, null=True)),
                ('specializations', models.JSONField(blank=True, default=list, help_text='AC brands the applicant specializes in')),
                ('personalDetailsConfirmed', models.BooleanField(default=False, help_text='Applicant confirmed personal details')),
                ('personalDetailsConfirmedAt', models.DateTimeField(blank=True, null=True)),
                ('bankName', models.CharField(blank=True, help_text='Bank name', max_length=100, null=True)),
                ('bankAccountNumber', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('bankAccountHolderName', models.CharField(blank=True, help_text='Account holder name', max_length=100, null=True)),
                ('bankInfoConfirmed', models.BooleanField(default=False, help_text='Applicant confirmed bank information')),
                ('bankInfoConfirmedAt', models.DateTimeField(blank=True, null=True)),
                ('payRate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly pay rate in SGD', max_digits=10, null=True)),
                ('coordinatorNotes', models.TextField(blank=True, help_text='Coordinator notes on application', max_length=1000, null=True)),
                ('coordinatorApproved', models.BooleanField(default=False, help_text='Coordinator approval confirmation')),
                ('coordinatorApprovedAt', models.DateTimeField(blank=True, null=True)),
                ('applicationStatus', models.CharField(choices=[('personal_details', 'Personal Details Pending'), ('bank_info', 'Bank Information Pending'), ('coordinator_review', 'Awaiting Coordinator Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='personal_details', help_text='Current stage of application', max_length=30)),
                ('coordinatorId', models.ForeignKey(blank=True, help_text='Coordinator who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_applications', to='backend_api.coordinators')),
                ('createdTechnician', models.ForeignKey(blank=True, help_text='The technician account created from this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_application', to='backend_api.technicians')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dayOfWeek', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('startTime', models.CharField(help_text='Start time in HH:MM format (e.g., 09:00)', max_length=5)),
                ('endTime', models.CharField(help_text='End time in HH:MM format (e.g., 17:00)', max_length=5)),
                ('specificDate', models.DateField(blank=True, help_text='Specific date override (e.g., leave day)', null=True)),
                ('isAvailable', models.BooleanField(default=True, help_text='False for leave/unavailable days')),
                ('technicianId', models.ForeignKey(db_column='technicianId', on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='backend_api.technicians')),
            ],
            options={
                'ordering': ['technicianId', 'dayOfWeek', 'specificDate'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('senderType', models.CharField(help_text='customer, coordinator, or technician', max_length=20)),
                ('senderId', models.UUIDField(help_text='ID of the sender')),
                ('senderName', models.CharField(help_text='Name of sender', max_length=50)),
                ('recipientType', models.CharField(help_text='customer, coordinator, or technician', max_length=20)),
                ('recipientId', models.UUIDField(help_text='ID of the recipient')),
                ('recipientName', models.CharField(help_text='Name of recipient', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('isRead', models.BooleanField(default=False, help_text='Whether the recipient has read the message')),
                ('readAt', models.DateTimeField(blank=True, help_text='When the message was read', null=True)),
                ('relatedAppointment', models.ForeignKey(blank=True, help_text='Optional related appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='backend_api.appointments')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customerName', models.CharField(max_length=50)),
                ('customerPostalCode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Postal code must be exactly 6 digits.')])),
                ('customerLocation', models.CharField(max_length=32, null=True)),
                ('customerAddress', models.CharField(max_length=50)),
                ('customerPhone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be exactly 8 digits.')])),
                ('customerPassword', models.CharField(max_length=128)),
                ('customerEmail', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('pendingPenaltyFee', models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated penalty fees for excessive cancellations', max_digits=10)),
                ('customerRating', models.DecimalField(decimal_places=2, default=5.0, help_text='Average rating from technicians (1-5), default 5', max_digits=3)),
                ('ratingCount', models.IntegerField(default=0, help_text='Number of ratings received from technicians')),
            ],
            options={
                'indexes': [models.Index(fields=['customerPhone'], name='customer_phone_idx'), models.Index(fields=['customerEmail'], name='customer_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerAirconDevices',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airconName', models.CharField(max_length=50, null=True)),
                ('numberOfUnits', models.IntegerField(default=1)),
                ('airconType', models.CharField(choices=[('industrial', 'Industrial'), ('split', 'Split'), ('window', 'Window'), ('centralized', 'Centralized'), ('floor_mounted', 'Floor Mounted'), ('portable', 'Portable')], default='split', max_length=20)),
                ('lastServiceMonth', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('remarks', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('lastServiceDate', models.BigIntegerField(blank=True, default=None, null=True)),
                ('airconCatalogId', models.ForeignKey(blank=True, db_column='airconCatalogId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_devices', to='backend_api.airconcatalogs')),
                ('customerId', models.ForeignKey(db_column='customerId', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aircon_devices', to='backend_api.customers')),
            ],
            options={
                'ordering': ['customerId', 'airconName'],
            },
        ),
        migrations.AddIndex(
            model_name='coordinators',
            index=models.Index(fields=['coordinatorEmail'], name='coordinator_email_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinators',
            index=models.Index(fields=['coordinatorPhone'], name='coordinator_phone_idx'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='customerId',
            field=models.ForeignKey(db_column='customerId', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='backend_api.customers'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='technicianId',
            field=models.ForeignKey(blank=True, db_column='technicianId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='backend_api.technicians'),
        ),
        migrations.AddField(
            model_name='appointmentrating',
            name='appointment',
            field=models.ForeignKey(db_column='appointmentId', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='backend_api.appointments'),
        ),
        migrations.AddIndex(
            model_name='airconcatalogs',
            index=models.Index(fields=['airconBrand'], name='aircon_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='airconcatalogs',
            index=models.Index(fields=['airconModel'], name='aircon_model_idx'),
        ),
        migrations.AddConstraint(
            model_name='airconcatalogs',
            constraint=models.UniqueConstraint(fields=('airconBrand', 'airconModel'), name='unique_aircon_brand_model'),
        ),
        migrations.AddIndex(
            model_name='technicianpasswordresettoken',
            index=models.Index(fields=['token'], name='backend_api_token_b72ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianpasswordresettoken',
            index=models.Index(fields=['technician'], name='backend_api_technic_a13a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianpasswordresettoken',
            index=models.Index(fields=['expiresAt'], name='backend_api_expires_6a7b19_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianhiringapplication',
            index=models.Index(fields=['nric'], name='backend_api_nric_a581c6_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianhiringapplication',
            index=models.Index(fields=['applicationStatus'], name='backend_api_applica_ace3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianhiringapplication',
            index=models.Index(fields=['-created_at'], name='backend_api_created_06bd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianavailability',
            index=models.Index(fields=['technicianId', 'dayOfWeek'], name='backend_api_technic_1b046c_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianavailability',
            index=models.Index(fields=['technicianId', 'specificDate'], name='backend_api_technic_353ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianavailability',
            index=models.Index(fields=['isAvailable'], name='backend_api_isAvail_eb60f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicianavailability',
            constraint=models.UniqueConstraint(condition=models.Q(('specificDate__isnull', True)), fields=('technicianId', 'dayOfWeek'), name='unique_tech_day_schedule'),
        ),
        migrations.AddConstraint(
            model_name='technicianavailability',
            constraint=models.UniqueConstraint(condition=models.Q(('specificDate__isnull', False)), fields=('technicianId', 'specificDate'), name='unique_tech_specific_date'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['senderId', 'senderType'], name='backend_api_senderI_6d0135_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['recipientId', 'recipientType'], name='backend_api_recipie_99aa71_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['isRead'], name='backend_api_isRead_1cad43_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['-created_at'], name='backend_api_created_0e262e_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraircondevices',
            index=models.Index(fields=['customerId'], name='backend_api_custome_6bd9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraircondevices',
            index=models.Index(fields=['airconType'], name='backend_api_airconT_551234_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraircondevices',
            constraint=models.UniqueConstraint(fields=('customerId', 'airconName'), name='uniq_device_name_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='appointments',
            constraint=models.CheckConstraint(check=models.Q(('appointmentEndTime__gt', models.F('appointmentStartTime'))), name='appt_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='appointmentrating',
            index=models.Index(fields=['appointment'], name='backend_api_appoint_010c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrating',
            index=models.Index(fields=['ratedBy'], name='backend_api_ratedBy_5d0fbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrating',
            constraint=models.UniqueConstraint(fields=('appointment', 'ratedBy'), name='unique_rating_per_appointment_direction'),
        ),
    ]
