# Generated by Django 5.0.1 on 2024-03-04 13:35

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirconCatalogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('airconBrand', models.CharField(max_length=50)),
                ('airconModel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('appointmentStartTime', models.BigIntegerField(default=None)),
                ('appointmentEndTime', models.BigIntegerField(default=None)),
                ('airconToService', models.JSONField(default=None)),
                ('customerFeedback', models.TextField(default=None, max_length=500, null=True)),
                ('appointmentStatus', models.CharField(choices=[('1', 'Pending'), ('2', 'Confirmed'), ('3', 'Completed'), ('4', 'Cancelled')], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coordinatorName', models.CharField(max_length=50)),
                ('coordinatorEmail', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('coordinatorPhone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$')])),
                ('coordinatorPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customerName', models.CharField(max_length=50)),
                ('customerPostalCode', models.CharField(max_length=6)),
                ('customerLocation', models.CharField(max_length=32, null=True)),
                ('customerAddress', models.CharField(max_length=50)),
                ('customerPhone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$')])),
                ('customerPassword', models.CharField(max_length=50)),
                ('customerEmail', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('technicianName', models.CharField(max_length=50)),
                ('technicianPostalCode', models.CharField(max_length=6)),
                ('technicianAddress', models.CharField(max_length=50)),
                ('technicianLocation', models.CharField(max_length=32, null=True)),
                ('technicianPhone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$')])),
                ('technicianPassword', models.CharField(max_length=50)),
                ('technicianStatus', models.CharField(choices=[('1', 'Available'), ('2', 'Unavailable')], default=1, max_length=1)),
                ('technicianTravelType', models.CharField(default='walk', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestedDateTime', models.BigIntegerField(default=None, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('reason', models.TextField(default=None, max_length=500)),
                ('remark', models.CharField(default=None, max_length=500, null=True)),
                ('appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_api.appointments')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAirconDevices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airconName', models.CharField(max_length=50, null=True)),
                ('lastServiceDate', models.BigIntegerField(default=None, null=True)),
                ('airconCatalogId', models.ForeignKey(db_column='airconCatalogId', default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_api.airconcatalogs')),
                ('customerId', models.ForeignKey(db_column='customerId', default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_api.customers')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='customerId',
            field=models.ForeignKey(db_column='customerId', default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_api.customers'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='technicianId',
            field=models.ForeignKey(db_column='technicianId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.technicians'),
        ),
    ]
