# Generated by Django 5.2.7 on 2025-10-30 07:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airconcatalogs',
            options={'ordering': ['airconBrand', 'airconModel']},
        ),
        migrations.AlterModelOptions(
            name='appointmentrequest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coordinators',
            options={'ordering': ['coordinatorName']},
        ),
        migrations.AlterModelOptions(
            name='customeraircondevices',
            options={'ordering': ['customerId', 'airconName']},
        ),
        migrations.AlterModelOptions(
            name='technicians',
            options={'ordering': ['technicianName']},
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='requestedDateTime',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='airconcatalogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airconcatalogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coordinators',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinators',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customeraircondevices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraircondevices',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='technicians',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicians',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='airconToService',
            field=models.JSONField(default=list, help_text='List of customerAirconDevices IDs'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointmentEndTime',
            field=models.BigIntegerField(help_text='Unix epoch seconds'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointmentStartTime',
            field=models.BigIntegerField(help_text='Unix epoch seconds'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='customerId',
            field=models.ForeignKey(db_column='customerId', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='backend_api.customers'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='technicianId',
            field=models.ForeignKey(blank=True, db_column='technicianId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='backend_api.technicians'),
        ),
        migrations.AlterField(
            model_name='customeraircondevices',
            name='airconCatalogId',
            field=models.ForeignKey(db_column='airconCatalogId', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_devices', to='backend_api.airconcatalogs'),
        ),
        migrations.AlterField(
            model_name='customeraircondevices',
            name='customerId',
            field=models.ForeignKey(db_column='customerId', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aircon_devices', to='backend_api.customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerPhone',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be exactly 8 digits.')]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerPostalCode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Postal code must be exactly 6 digits.')]),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='technicianPhone',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be exactly 8 digits.')]),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='technicianPostalCode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Postal code must be exactly 6 digits.')]),
        ),
        migrations.AddIndex(
            model_name='airconcatalogs',
            index=models.Index(fields=['airconBrand'], name='aircon_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='airconcatalogs',
            index=models.Index(fields=['airconModel'], name='aircon_model_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinators',
            index=models.Index(fields=['coordinatorEmail'], name='coordinator_email_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinators',
            index=models.Index(fields=['coordinatorPhone'], name='coordinator_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraircondevices',
            index=models.Index(fields=['customerId'], name='backend_api_custome_6bd9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraircondevices',
            index=models.Index(fields=['airconCatalogId'], name='backend_api_airconC_64a367_idx'),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['customerPhone'], name='customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['customerEmail'], name='customer_email_idx'),
        ),
        migrations.AddIndex(
            model_name='technicians',
            index=models.Index(fields=['technicianStatus'], name='backend_api_technic_5234e8_idx'),
        ),
        migrations.AddIndex(
            model_name='technicians',
            index=models.Index(fields=['technicianPhone'], name='backend_api_technic_c024c8_idx'),
        ),
        migrations.AddIndex(
            model_name='technicians',
            index=models.Index(fields=['technicianPostalCode'], name='backend_api_technic_0df0b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='airconcatalogs',
            constraint=models.UniqueConstraint(fields=('airconBrand', 'airconModel'), name='unique_aircon_brand_model'),
        ),
        migrations.AddConstraint(
            model_name='appointments',
            constraint=models.CheckConstraint(check=models.Q(('appointmentEndTime__gt', models.F('appointmentStartTime'))), name='appt_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='customeraircondevices',
            constraint=models.UniqueConstraint(fields=('customerId', 'airconName'), name='uniq_device_name_per_customer'),
        ),
    ]
