# Generated by Django 4.2.5 on 2026-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraircondevices',
            name='airconType',
            field=models.CharField(choices=[('daikin', 'Daikin'), ('mitsubishi', 'Mitsubishi'), ('panasonic', 'Panasonic'), ('lg', 'LG'), ('samsung', 'Samsung'), ('fujitsu', 'Fujitsu'), ('sharp', 'Sharp'), ('toshiba', 'Toshiba'), ('hitachi', 'Hitachi'), ('york', 'York'), ('other', 'Other')], default='daikin', max_length=20),
        ),
    ]
