# Generated by Django 4.2.5 on 2026-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_customeraircondevices_aircontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians',
            name='technicianTravelType',
            field=models.CharField(blank=True, choices=[('own_vehicle', 'Own Vehicle'), ('rented_vehicle', 'Rented Vehicle'), ('company_vehicle', 'Company Vehicle')], default=None, max_length=20, null=True),
        ),
    ]
