# Generated by Django 5.2.7 on 2025-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_airconcatalogs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='cancellationReason',
            field=models.TextField(blank=True, default=None, help_text='Reason for cancellation', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='cancelledAt',
            field=models.DateTimeField(blank=True, help_text='Timestamp of cancellation', null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='cancelledBy',
            field=models.CharField(blank=True, help_text='Role of person who cancelled (technician/coordinator)', max_length=50, null=True),
        ),
    ]
