# Generated by Django 5.2.7 on 2025-11-13 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_appointments_cancellationreason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('senderType', models.CharField(help_text='customer, coordinator, or technician', max_length=20)),
                ('senderId', models.UUIDField(help_text='ID of the sender')),
                ('senderName', models.CharField(help_text='Name of sender', max_length=50)),
                ('recipientType', models.CharField(help_text='customer, coordinator, or technician', max_length=20)),
                ('recipientId', models.UUIDField(help_text='ID of the recipient')),
                ('recipientName', models.CharField(help_text='Name of recipient', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('isRead', models.BooleanField(default=False, help_text='Whether the recipient has read the message')),
                ('readAt', models.DateTimeField(blank=True, help_text='When the message was read', null=True)),
                ('relatedAppointment', models.ForeignKey(blank=True, help_text='Optional related appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='backend_api.appointments')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['senderId', 'senderType'], name='backend_api_senderI_6d0135_idx'), models.Index(fields=['recipientId', 'recipientType'], name='backend_api_recipie_99aa71_idx'), models.Index(fields=['isRead'], name='backend_api_isRead_1cad43_idx'), models.Index(fields=['-created_at'], name='backend_api_created_0e262e_idx')],
            },
        ),
    ]
