# Generated by Django 4.2.5 on 2026-03-07 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_set_all_technicians_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='telegramChatId',
            field=models.BigIntegerField(blank=True, default=None, help_text='Telegram chat ID for notifications', null=True),
        ),
        migrations.AddField(
            model_name='technicians',
            name='telegramChatId',
            field=models.BigIntegerField(blank=True, default=None, help_text='Telegram chat ID for notifications', null=True),
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('userType', models.CharField(help_text='customer or technician', max_length=20)),
                ('userId', models.UUIDField(help_text='ID of the customer or technician')),
                ('expiresAt', models.DateTimeField(help_text='Token expiration time (10 min)')),
                ('isUsed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='backend_api_token_fe1533_idx'), models.Index(fields=['userId', 'userType'], name='backend_api_userId_8fd697_idx')],
            },
        ),
    ]
