# Generated by Django 4.2.5 on 2026-01-13 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianHiringApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('applicantName', models.CharField(help_text='Full name of applicant', max_length=100)),
                ('nric', models.CharField(help_text='NRIC number', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[STFG]\\d{7}[A-Z]$', 'NRIC must be in valid Singapore format (e.g., S1234567A)')])),
                ('citizenship', models.CharField(help_text='Citizenship status', max_length=50)),
                ('applicantAddress', models.CharField(help_text='Full residential address', max_length=200)),
                ('applicantPostalCode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Postal code must be exactly 6 digits.')])),
                ('applicantPhone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be exactly 8 digits.')])),
                ('applicantEmail', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('workExperience', models.TextField(help_text='Work experience details', max_length=2000)),
                ('resumeFile', models.FileField(blank=True, help_text='Resume upload', null=True, upload_to='resumes/')),
                ('resumeFileName', models.CharField(blank=True, help_text='Original resume filename', max_length=255, null=True)),
                ('hasCriminalRecord', models.BooleanField(default=False, help_text='Criminal record declaration')),
                ('criminalRecordDetails', models.TextField(blank=True, help_text='Details if criminal record exists', max_length=1000, null=True)),
                ('personalDetailsConfirmed', models.BooleanField(default=False, help_text='Applicant confirmed personal details')),
                ('personalDetailsConfirmedAt', models.DateTimeField(blank=True, null=True)),
                ('bankName', models.CharField(blank=True, help_text='Bank name', max_length=100, null=True)),
                ('bankAccountNumber', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('bankAccountHolderName', models.CharField(blank=True, help_text='Account holder name', max_length=100, null=True)),
                ('bankInfoConfirmed', models.BooleanField(default=False, help_text='Applicant confirmed bank information')),
                ('bankInfoConfirmedAt', models.DateTimeField(blank=True, null=True)),
                ('payRate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly pay rate in SGD', max_digits=10, null=True)),
                ('coordinatorNotes', models.TextField(blank=True, help_text='Coordinator notes on application', max_length=1000, null=True)),
                ('coordinatorApproved', models.BooleanField(default=False, help_text='Coordinator approval confirmation')),
                ('coordinatorApprovedAt', models.DateTimeField(blank=True, null=True)),
                ('applicationStatus', models.CharField(choices=[('personal_details', 'Personal Details Pending'), ('bank_info', 'Bank Information Pending'), ('coordinator_review', 'Awaiting Coordinator Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='personal_details', help_text='Current stage of application', max_length=30)),
                ('coordinatorId', models.ForeignKey(blank=True, help_text='Coordinator who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_applications', to='backend_api.coordinators')),
                ('createdTechnician', models.ForeignKey(blank=True, help_text='The technician account created from this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_application', to='backend_api.technicians')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nric'], name='backend_api_nric_a581c6_idx'), models.Index(fields=['applicationStatus'], name='backend_api_applica_ace3fb_idx'), models.Index(fields=['-created_at'], name='backend_api_created_06bd3b_idx')],
            },
        ),
    ]
