# Generated by Django 4.2.5 on 2026-01-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_technicianhiringapplication'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customeraircondevices',
            name='backend_api_airconC_64a367_idx',
        ),
        migrations.AddField(
            model_name='customeraircondevices',
            name='airconType',
            field=models.CharField(choices=[('industrial', 'Industrial'), ('split', 'Split'), ('window', 'Window'), ('centralized', 'Centralized'), ('floor_mounted', 'Floor Mounted'), ('portable', 'Portable')], default='split', max_length=20),
        ),
        migrations.AddField(
            model_name='customeraircondevices',
            name='lastServiceMonth',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='customeraircondevices',
            name='numberOfUnits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customeraircondevices',
            name='remarks',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customeraircondevices',
            name='airconCatalogId',
            field=models.ForeignKey(blank=True, db_column='airconCatalogId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_devices', to='backend_api.airconcatalogs'),
        ),
        migrations.AlterField(
            model_name='customeraircondevices',
            name='lastServiceDate',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='customeraircondevices',
            index=models.Index(fields=['airconType'], name='backend_api_airconT_551234_idx'),
        ),
    ]
