# Generated by Django 4.2.5 on 2026-03-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_customers_telegramchatid_technicians_telegramchatid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='customerId',
            field=models.ForeignKey(db_column='customerId', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='backend_api.customers'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='technicianId',
            field=models.ForeignKey(blank=True, db_column='technicianId', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='backend_api.technicians'),
        ),
    ]
