# Generated by Django 4.2.5 on 2026-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_customeraircondevices_backend_api_airconc_64a367_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians',
            name='technicianTravelType',
            field=models.CharField(choices=[('own_vehicle', 'Own Vehicle'), ('company_vehicle', 'Company Vehicle'), ('rental_van', 'Rental Van')], default='own_vehicle', max_length=20),
        ),
    ]
