# Generated by Django 5.1.15 on 2026-03-27 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_protect_fks_widen_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='backend_api_token_100a4b_idx',
            old_name='backend_api_token_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='backend_api_userId_e59264_idx',
            old_name='backend_api_userid_type_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='backend_api_expires_fb70f8_idx',
            old_name='backend_api_expires_idx',
        ),
        migrations.AlterField(
            model_name='appointmentrating',
            name='rating',
            field=models.IntegerField(help_text='1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointmentStatus',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Confirmed'), ('3', 'Completed'), ('4', 'Cancelled')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='technicianStatus',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Unavailable')], default='1', max_length=1),
        ),
        migrations.AddIndex(
            model_name='appointments',
            index=models.Index(fields=['appointmentStatus'], name='appt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointments',
            index=models.Index(fields=['customerId', 'appointmentStatus'], name='appt_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointments',
            index=models.Index(fields=['customerId', 'appointmentStatus', 'cancelledAt'], name='appt_cust_cancel_idx'),
        ),
        migrations.AddIndex(
            model_name='appointments',
            index=models.Index(fields=['technicianId', 'appointmentStatus'], name='appt_tech_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointments',
            index=models.Index(fields=['technicianId', 'cancelledBy', 'cancelledAt'], name='appt_tech_cancel_idx'),
        ),
        migrations.AddIndex(
            model_name='appointments',
            index=models.Index(fields=['appointmentStartTime'], name='appt_start_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_1_to_5'),
        ),
    ]
