# Generated by Django 4.2.5 on 2026-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_update_technician_travel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='paymentMethod',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paynow', 'PayLah/PayNow')], default='cash', help_text='Customer selected payment method', max_length=20),
        ),
    ]
