# Generated by Django 4.2.5 on 2026-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customerLocation',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='technicianLocation',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
