# Generated by Django 4.2.5 on 2026-01-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_add_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='lastDrawnSalary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last drawn monthly salary in SGD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='lastEmployedYear',
            field=models.IntegerField(blank=True, help_text='Year when last employed', null=True),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='previousEmployer',
            field=models.CharField(blank=True, help_text='Name of previous employer(s)', max_length=200, null=True),
        ),
    ]
