# Generated by Django 4.2.5 on 2026-01-21 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_add_previous_employer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='isMedicallyFit',
            field=models.BooleanField(default=False, help_text='Declaration of medical fitness to work'),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='languagesSpoken',
            field=models.CharField(default='', help_text='Languages spoken (comma-separated)', max_length=200),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='medicalFitnessConfirmedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='nextOfKinContact',
            field=models.CharField(default='', help_text='Contact number of next of kin', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone must be exactly 8 digits.')]),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='nextOfKinName',
            field=models.CharField(default='', help_text='Name of next of kin', max_length=100),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='nextOfKinRelationship',
            field=models.CharField(default='', help_text='Relationship with next of kin', max_length=50),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='profilePhoto',
            field=models.ImageField(blank=True, help_text='Profile photo of applicant', null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='profilePhotoFileName',
            field=models.CharField(blank=True, help_text='Original profile photo filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='race',
            field=models.CharField(default='', help_text='Race of applicant', max_length=50),
        ),
    ]
