# Generated by Django 4.2.5 on 2026-01-22 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_add_hiring_nok_race_medical_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dayOfWeek', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('startTime', models.CharField(help_text='Start time in HH:MM format (e.g., 09:00)', max_length=5)),
                ('endTime', models.CharField(help_text='End time in HH:MM format (e.g., 17:00)', max_length=5)),
                ('specificDate', models.DateField(blank=True, help_text='Specific date override (e.g., leave day)', null=True)),
                ('isAvailable', models.BooleanField(default=True, help_text='False for leave/unavailable days')),
                ('technicianId', models.ForeignKey(db_column='technicianId', on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='backend_api.technicians')),
            ],
            options={
                'ordering': ['technicianId', 'dayOfWeek', 'specificDate'],
                'indexes': [models.Index(fields=['technicianId', 'dayOfWeek'], name='backend_api_technic_1b046c_idx'), models.Index(fields=['technicianId', 'specificDate'], name='backend_api_technic_353ac5_idx'), models.Index(fields=['isAvailable'], name='backend_api_isAvail_eb60f3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='technicianavailability',
            constraint=models.UniqueConstraint(condition=models.Q(('specificDate__isnull', True)), fields=('technicianId', 'dayOfWeek'), name='unique_tech_day_schedule'),
        ),
        migrations.AddConstraint(
            model_name='technicianavailability',
            constraint=models.UniqueConstraint(condition=models.Q(('specificDate__isnull', False)), fields=('technicianId', 'specificDate'), name='unique_tech_specific_date'),
        ),
    ]
