# Generated by Django 4.2.5 on 2026-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_technicianavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='pendingPenaltyFee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated penalty fees for excessive cancellations', max_digits=10),
        ),
    ]
