# Generated by Django 4.2.5 on 2026-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_add_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='drivingLicense',
            field=models.ImageField(blank=True, help_text='Driving license photo', null=True, upload_to='driving_licenses/'),
        ),
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='drivingLicenseFileName',
            field=models.CharField(blank=True, help_text='Original driving license filename', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='technicianTravelType',
            field=models.CharField(blank=True, choices=[('own_vehicle', 'Own Vehicle'), ('company_vehicle', 'Company Vehicle'), ('rental_van', 'Rental Van')], default=None, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='appointmentrating',
            index=models.Index(fields=['appointment'], name='backend_api_appoint_010c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrating',
            index=models.Index(fields=['ratedBy'], name='backend_api_ratedBy_5d0fbc_idx'),
        ),
        migrations.AlterModelTable(
            name='appointmentrating',
            table=None,
        ),
    ]
