# Generated by Django 4.2.5 on 2026-02-12 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0016_add_driving_license_and_nullable_travel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianPasswordResetToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expiresAt', models.DateTimeField(help_text='Token expiration time')),
                ('isUsed', models.BooleanField(default=False, help_text='Whether token has been used')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='backend_api.technicians')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='backend_api_token_b72ac3_idx'), models.Index(fields=['technician'], name='backend_api_technic_a13a2a_idx'), models.Index(fields=['expiresAt'], name='backend_api_expires_6a7b19_idx')],
            },
        ),
    ]
