# Generated by Django 4.2.5 on 2026-02-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='deactivatedAt',
            field=models.DateTimeField(blank=True, help_text='When the technician was deactivated', null=True),
        ),
        migrations.AddField(
            model_name='technicians',
            name='deactivationReason',
            field=models.TextField(blank=True, help_text='Reason for deactivation', null=True),
        ),
        migrations.AddField(
            model_name='technicians',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Whether technician is currently employed/active'),
        ),
        migrations.AddIndex(
            model_name='technicians',
            index=models.Index(fields=['isActive'], name='backend_api_isActiv_eab08d_idx'),
        ),
    ]
