# Generated by Django 4.2.5 on 2026-02-12 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_add_technician_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='technicianEmail',
            field=models.CharField(blank=True, help_text='Email address for notifications', max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddIndex(
            model_name='technicians',
            index=models.Index(fields=['technicianEmail'], name='backend_api_technic_ff7cae_idx'),
        ),
    ]
