# Generated by Django 4.2.5 on 2026-02-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0019_add_technician_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianhiringapplication',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text='AC brands the applicant specializes in'),
        ),
        migrations.AddField(
            model_name='technicians',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text='List of AC brands the technician specializes in'),
        ),
    ]
